### PR TITLE
update hashie version

### PR DESCRIPTION
**Pull request by jsorchik**

### CODE REVIEW

**Comment by PericlesTheo** [comment]
Any updates with this?

**Comment by chriswarren** [comment]
No - since the pull request was closed I haven't been watching it. If the PR gets reopened or another one is made we'll add it in.

**Comment by PericlesTheo** [comment]
Thanks Chris, will issue a new one today, hopefully.

**Comment by PericlesTheo** [comment]
@chriswarren master is currently red with

```ruby
rspec ./spec/desk/api_spec.rb:51 # Desk::API with module configuration with class configuration should override module configuration
rspec ./spec/desk/api_spec.rb:60 # Desk::API with module configuration with class configuration after initilization should override module configuration after initialization
```

What would you like me to do?

**Pull request closed without merging**
